name: Edit Image with Gemini

on:
  workflow_dispatch:
    inputs:
      image_base64:
        description: 'Base64 encoded image data'
        required: true
      prompt:
        description: 'Edit prompt'
        required: true
        default: 'Add a llama next to me'
      google_api_key:  # הוספת הפרמטר הזה
        description: 'Google API Key'
        required: true

jobs:
  edit-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-genai pillow requests

      - name: Decode base64 image
        run: |
          echo "${{ github.event.inputs.image_base64 }}" | base64 --decode > input_image.png

      - name: Run image edit
        env:
          GOOGLE_API_KEY: ${{ github.event.inputs.google_api_key }}  # הוספת המשתנה
        run: |
          python edit_image.py "input_image.png" "${{ github.event.inputs.prompt }}"
