name: Edit Image with Gemini

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'URL of the input image'
        required: true
      prompt:
        description: 'Edit prompt'
        required: true
        default: 'Add a llama next to me'
      google_api_key:
        description: 'Google API Key'
        required: true

jobs:
  edit-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-genai pillow requests

      - name: Download image from URL
        run: |
          curl -L -o input_image.png "${{ github.event.inputs.image_url }}"

      - name: Run image edit
        env:
          GOOGLE_API_KEY: ${{ github.event.inputs.google_api_key }}
        run: |
          python edit_image.py "input_image.png" "${{ github.event.inputs.prompt }}"
          
      - name: Upload edited image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: edited-image
          path: edited_image.png
          retention-days: 1
