name: Edit Image with Gemini

on:
  workflow_dispatch:
    inputs:
      # --- CHANGED ---
      # We now expect a base64 encoded string, not a URL
      image_base64:
        description: 'Base64 encoded image data'
        required: true
      prompt:
        description: 'Edit prompt'
        required: true
        default: 'Add a llama next to me'

jobs:
  edit-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-genai pillow requests

      # --- NEW STEP ---
      # This step decodes the base64 string back into an image file
      - name: Decode base64 image
        run: |
          echo "${{ github.event.inputs.image_base64 }}" | base64 --decode > input_image.png

      - name: Run image edit
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        # --- CHANGED ---
        # The python script now gets the local file path 'input_image.png'
        run: |
          python edit_image.py "input_image.png" "${{ github.event.inputs.prompt }}"

      - name: Upload edited image
        uses: actions/upload-artifact@v4
        with:
          name: edited-image
          path: edited_image.png
