name: Suno Song Generator

on:
  workflow_dispatch:

jobs:
  generate-song:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install suno-api
        run: pip install suno-api

      - name: Run Suno Song Script
        env:
          SUNO_COOKIE: ${{ secrets.SUNO_COOKIE }}
        run: |
          python suno_song.py

      - name: Upload song artifact
        uses: actions/upload-artifact@v4
        with:
          name: suno-song
          path: |
            song.mp3
            lyrics.txt
