name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

jobs:
  download-and-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yt-dlp

      - name: Install ffmpeg if not exists
        run: |
          if ! command -v ffmpeg &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends ffmpeg
          else
            echo "ffmpeg already installed"
          fi

      - name: Download cookies.txt from repository (if exists)
        run: |
          if [ -f cookies.txt ]; then
            echo "cookies.txt found"
          else
            echo "No cookies.txt found"
          fi

      - name: Download video
        id: download
        run: |
          # Run the script and capture the output
          output=$(python download_and_zip1.py "${{ github.event.inputs.video_url }}" | grep "נשמר קובץ הווידאו בשם: ")
          # Extract the filename from the output
          FILENAME=$(echo "$output" | cut -d' ' -f6)
          # Set the output for the next step
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "Downloaded file: $FILENAME"

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-video
          path: ${{ steps.download.outputs.filename }}
