name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

jobs:
  download-and-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yt-dlp

      - name: Install ffmpeg if not exists
        run: |
          if ! command -v ffmpeg &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends ffmpeg
          else
            echo "ffmpeg already installed"
          fi

      - name: Download cookies.txt from repository (if exists)
        run: |
          if [ -f cookies.txt ]; then
            echo "cookies.txt found"
          else
            echo "No cookies.txt found"
          fi

      - name: Download video(s)
        id: download
        run: |
          python download_and_zip1.py "${{ github.event.inputs.video_url }}"
          echo "List from downloaded_files.txt (if created):"
          cat downloaded_files.txt || true

      # Single video case (uses 'file' output)
      - name: Upload video artifact
        if: ${{ always() && steps.download.outputs.file != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: youtube-video
          path: ${{ steps.download.outputs.file }}

      # Playlist or multiple files (uses multiline 'files' output)
      - name: Upload video artifacts (multiple)
        if: ${{ always() && steps.download.outputs.files != '' && steps.download.outputs.file == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: youtube-videos
          path: ${{ steps.download.outputs.files }}
