name: Monologue Generator

on:
  workflow_dispatch:

jobs:
  generate-monologue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: List files
        run: ls -l

      - name: Print env
        run: env

      - name: Run monologue script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python monolog.py

      - name: Upload monologue audio
        uses: actions/upload-artifact@v4
        with:
          name: monologue-audio
          path: podcast.wav

      - name: Upload monologue text
        uses: actions/upload-artifact@v4
        with:
          name: monologue-text
          path: monologue.txt
